# Generated by Django 5.1.3 on 2024-11-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nm', models.CharField(max_length=50)),
                ('Em', models.CharField(max_length=50)),
                ('Ph', models.BigIntegerField()),
                ('Dg', models.CharField(max_length=50)),
                ('Dp', models.CharField(max_length=50)),
                ('Ofid', models.BigIntegerField()),
                ('Pass', models.BigIntegerField()),
            ],
        ),
    ]
