# Generated by Django 5.1.3 on 2024-11-13 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Management_App', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
