# Generated by Django 5.1.3 on 2024-12-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Management_App', '0003_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MonthlyRevenue', models.CharField(max_length=50)),
                ('Month', models.CharField(max_length=50)),
            ],
        ),
    ]
